name: Go CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    name: Validate and Build Go Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.1

    - name: Install dependencies
      working-directory: shop-app
      run: |
        go mod tidy

    - name: Run gofmt
      working-directory: shop-app
      run: |
        gofmt -w .

    - name: Build the application
      working-directory: shop-app
      run: |
        go build -o app .
