name: Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  api-test:
    name: 'API Unit Tests'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Log Message to Console
        run: echo "No tests added yet."